ingress-nginx:
  Enabled: true
OperationsCenter:
  HostName: "cloudbees-ci.example.com"
  Platform: "eks"
  JavaOpts: "-Dcb.BeekeeperProp.noFullUpgrade=true"
  Tolerations:
    - key: partition
      operator: Equal
      value: masters
      effect: NoSchedule
  NodeSelector:
    partition: "masters"
  Annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
Master:
  JavaOpts: "-Dcb.BeekeeperProp.noFullUpgrade=true"
Hibernation:
  Enabled: true
