nginx-ingress:
  Enabled: true
OperationsCenter:
  HostName: "xxx-111.us-east-1.elb.amazonaws.com"
  JavaOpts: "-Dcb.BeekeeperProp.noFullUpgrade=true"
  Tolerations:
    - key: partition
      operator: Equal
      value: masters
      effect: NoSchedule
  NodeSelector:
    partition: "masters"
  Annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  Ingress:
    Annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:XXXXXXXX:certificate/XXXXXX-XXXXXXX-XXXXXXX-XXXXXXXX
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    tls: 
      Enable: true
      SecretName: core-example-com-tls

Masters:
  JavaOpts: "-Dcb.BeekeeperProp.noFullUpgrade=true"

